### ISSUE TITLE
Provide a way to limit max-parallel on CI

### ISSUE THREAD

**Issue by atomicpages** [bcomnes/npm-run-all2#116]
CI systems generally have restricted resources so it'd be great to limit the number of parallel processes via env var. I envision something like this:

```sh
MAX_PARALLEL_TASKS=4 npm-run-all -p build:*
```

a more verbose example with gitlab CI might look like:

```yml
build:
  stage: build
  script:
    - export MAX_PARALLEL_TASKS=2
    - npm ci
    - npx npm-run-all -p lint test check-types
    - npm run build
```

I'd be happy to make a MR for this if the community is interested. LMK! 🙏
